blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/QRun-IO/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/QRun-IO/qqq/wiki
    about: Check the wiki for documentation and guides
